2022-12-06 14:01:52,566 INFO    MainThread:20788 [wandb_setup.py:_flush():68] Configure stats pid to 20788
2022-12-06 14:01:52,566 INFO    MainThread:20788 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Calculos\.config\wandb\settings
2022-12-06 14:01:52,566 INFO    MainThread:20788 [wandb_setup.py:_flush():68] Loading settings from d:\UniSergio\BasketScripts\WaB\wandb\settings
2022-12-06 14:01:52,566 INFO    MainThread:20788 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-12-06 14:01:52,566 INFO    MainThread:20788 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-12-06 14:01:52,566 ERROR   MainThread:20788 [wandb_setup.py:_flush():68] error
Traceback (most recent call last):
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 219, in setup
    init_config = parse_config(
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 14, in parse_config
    params = _to_dict(params)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 42, in _to_dict
    raise TypeError("config must be a dict or have a __dict__ attribute.")
TypeError: config must be a dict or have a __dict__ attribute.
2022-12-06 14:01:52,567 ERROR   MainThread:20788 [wandb_setup.py:_flush():68] error
Traceback (most recent call last):
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 219, in setup
    init_config = parse_config(
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 14, in parse_config
    params = _to_dict(params)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 42, in _to_dict
    raise TypeError("config must be a dict or have a __dict__ attribute.")
TypeError: config must be a dict or have a __dict__ attribute.
2022-12-06 14:01:52,567 ERROR   MainThread:20788 [wandb_setup.py:_flush():68] error
Traceback (most recent call last):
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_init.py", line 219, in setup
    init_config = parse_config(
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 14, in parse_config
    params = _to_dict(params)
  File "c:\Users\Calculos\miniconda3\envs\pytuurc\lib\site-packages\wandb\sdk\wandb_helper.py", line 42, in _to_dict
    raise TypeError("config must be a dict or have a __dict__ attribute.")
TypeError: config must be a dict or have a __dict__ attribute.
2022-12-06 14:01:52,567 INFO    MainThread:20788 [wandb_init.py:_log_setup():476] Logging user logs to d:\UniSergio\BasketScripts\WaB\wandb\run-20221206_140152-1rjvhnjw\logs\debug.log
2022-12-06 14:01:52,567 INFO    MainThread:20788 [wandb_init.py:_log_setup():477] Logging internal logs to d:\UniSergio\BasketScripts\WaB\wandb\run-20221206_140152-1rjvhnjw\logs\debug-internal.log
2022-12-06 14:01:52,567 INFO    MainThread:20788 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000023409648FA0>
2022-12-06 14:01:52,568 INFO    MainThread:20788 [wandb_init.py:init():516] calling init triggers
2022-12-06 14:01:52,568 INFO    MainThread:20788 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'num_neurons': 30, 'acti_fun': 'relu', 'batch_size': 150, 'epochs': 500, 'architecture': 'OneHiddenLayerL2', 'dataset': '2019-20_traditional', 'loss': 0.5697089433670044, 'acc': 0.7915000319480896, 'val_loss': 0.9285241365432739, 'val_acc': 0.6380000114440918}
2022-12-06 14:01:52,568 INFO    MainThread:20788 [wandb_init.py:init():569] starting backend
2022-12-06 14:01:52,568 INFO    MainThread:20788 [wandb_init.py:init():573] setting up manager
2022-12-06 14:01:52,569 INFO    MainThread:20788 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn, using: spawn
2022-12-06 14:01:52,571 INFO    MainThread:20788 [wandb_init.py:init():580] backend started and connected
2022-12-06 14:01:52,572 INFO    MainThread:20788 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2022-12-06 14:01:52,572 INFO    MainThread:20788 [wandb_run.py:_label_probe_notebook():1123] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-12-06 14:01:52,572 INFO    MainThread:20788 [wandb_init.py:init():658] updated telemetry
2022-12-06 14:01:52,572 INFO    MainThread:20788 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-12-06 14:01:53,877 INFO    MainThread:20788 [wandb_run.py:_on_init():2000] communicating current version
2022-12-06 14:01:54,092 INFO    MainThread:20788 [wandb_run.py:_on_init():2004] got version response 
2022-12-06 14:01:54,092 INFO    MainThread:20788 [wandb_init.py:init():728] starting run threads in backend
2022-12-06 14:01:56,886 INFO    MainThread:20788 [wandb_run.py:_console_start():1980] atexit reg
2022-12-06 14:01:56,886 INFO    MainThread:20788 [wandb_run.py:_redirect():1838] redirect: SettingsConsole.WRAP_RAW
2022-12-06 14:01:56,886 INFO    MainThread:20788 [wandb_run.py:_redirect():1903] Wrapping output streams.
2022-12-06 14:01:56,886 INFO    MainThread:20788 [wandb_run.py:_redirect():1925] Redirects installed.
2022-12-06 14:01:56,886 INFO    MainThread:20788 [wandb_init.py:init():765] run started, returning control to user process
2022-12-06 14:01:57,109 INFO    MainThread:20788 [wandb_run.py:_finish():1746] finishing run progettobasket/TTra1920runs/1rjvhnjw
2022-12-06 14:01:57,110 ERROR   MainThread:20788 [jupyter.py:save_history():440] Run pip install nbformat to save notebook history
2022-12-06 14:01:57,110 INFO    MainThread:20788 [jupyter.py:save_ipynb():378] not saving jupyter notebook
2022-12-06 14:01:57,110 INFO    MainThread:20788 [wandb_init.py:_jupyter_teardown():408] cleaning up jupyter logic
2022-12-06 14:01:57,110 INFO    MainThread:20788 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2022-12-06 14:01:57,110 INFO    MainThread:20788 [wandb_run.py:_restore():1932] restore
2022-12-06 14:01:57,110 INFO    MainThread:20788 [wandb_run.py:_restore():1938] restore done
2022-12-06 14:02:07,216 INFO    MainThread:20788 [wandb_run.py:_footer_history_summary_info():3377] rendering history
2022-12-06 14:02:07,217 INFO    MainThread:20788 [wandb_run.py:_footer_history_summary_info():3409] rendering summary
2022-12-06 14:02:07,221 INFO    MainThread:20788 [wandb_run.py:_footer_sync_info():3333] logging synced files
